services:
  - type: web
    name: public-infra-reporting
    env: node
    plan: free
    region: singapore
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
